/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.ADMIN;

import BACKEND.Gestor;
import javax.swing.JOptionPane;
import BACKEND.Sistema;
import SERIALIZACAO.Serializacao;

public class AdicionarGestor extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;

    public AdicionarGestor(Sistema sistema, Serializacao serializacao) {
        initComponents();

        this.sistema = sistema;
        this.serializacao = serializacao;
    }

    public void guardar() {
        if (jTextFieldNomeG.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza, por favor, o Nome!", "NOME EM FALTA", JOptionPane.WARNING_MESSAGE);
            jTextFieldNomeG.requestFocus();
            return;
        }
        if (jTextFieldUsernameG.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza, por favor, o Username!", "USERNAME EM FALTA", JOptionPane.WARNING_MESSAGE);
            jTextFieldUsernameG.requestFocus();
            return;
        }

        if (jTextFieldEmailG.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza, por favor, o Email!", "EMAIL EM FALTA", JOptionPane.WARNING_MESSAGE);
            jTextFieldEmailG.requestFocus();
            return;
        }

        if (jTextFieldPasswordG.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza, por favor, a password!", "PASSWORD EM FALTA", JOptionPane.WARNING_MESSAGE);
            jTextFieldPasswordG.requestFocus();
            return;
        }
        String username = jTextFieldUsernameG.getText().trim();
        String email = jTextFieldEmailG.getText().trim();
        if (sistema.getUtilizadores().existeUtilizador(username)) {
            JOptionPane.showMessageDialog(this, "Já existe um utilizador com esse username.", "UTILIZADOR EXISTENTE", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (sistema.getUtilizadores().verificarEmail(email)) {
            JOptionPane.showMessageDialog(this, "Já existe um utilizador com esse email.", "EMAIL EXISTENTE", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Gestor gestor = new Gestor(username, jTextFieldPasswordG.getText(), email, jTextFieldNomeG.getText().trim());
        sistema.getUtilizadores().adicionar(gestor);
        serializacao.guardar(sistema);
        JOptionPane.showMessageDialog(this, "Gestor criado com sucesso.");
        dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNomeG = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jButtonLimparGestor = new javax.swing.JButton();
        jTextFieldEmailG = new javax.swing.JTextField();
        jTextFieldUsernameG = new javax.swing.JTextField();
        jTextFieldPasswordG = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGuardarGestor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 80, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 80, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));
        getContentPane().add(jTextFieldNomeG, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 280, -1));

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 120, -1));

        jButtonLimparGestor.setText("Limpar");
        jButtonLimparGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparGestorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimparGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 110, -1));
        getContentPane().add(jTextFieldEmailG, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 280, -1));
        getContentPane().add(jTextFieldUsernameG, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 280, -1));
        getContentPane().add(jTextFieldPasswordG, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 420, 280, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 120, -1));

        jButtonGuardarGestor.setText("Guardar");
        jButtonGuardarGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarGestorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRONTEND/images/AdicionarGestor.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarGestorActionPerformed
        guardar();
    }//GEN-LAST:event_jButtonGuardarGestorActionPerformed

    private void jButtonLimparGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparGestorActionPerformed
        jTextFieldNomeG.setText(null);
        jTextFieldUsernameG.setText(null);
        jTextFieldEmailG.setText(null);
        jTextFieldPasswordG.setText(null);
    }//GEN-LAST:event_jButtonLimparGestorActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardarGestor;
    private javax.swing.JButton jButtonLimparGestor;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldEmailG;
    private javax.swing.JTextField jTextFieldNomeG;
    private javax.swing.JTextField jTextFieldPasswordG;
    private javax.swing.JTextField jTextFieldUsernameG;
    // End of variables declaration//GEN-END:variables
}
