/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.ADMIN;

import BACKEND.Gestor;
import BACKEND.Sistema;
import SERIALIZACAO.Serializacao;
import javax.swing.table.AbstractTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Gonçalo
 */
public class GerirGestores extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;
    private AbstractTableModel modeloTabelaGestores;

    public GerirGestores(Sistema sistema, Serializacao serializacao) {
        initComponents();
        this.sistema = sistema;
        this.serializacao = serializacao;
        this.modeloTabelaGestores = criarModeloTabelaGestores();
        jTableGestores.setModel(modeloTabelaGestores);

    }

    private AbstractTableModel criarModeloTabelaGestores() {
        String[] nomeColunas = {"Nome", "Username", "Email"};

        return new AbstractTableModel() {

            @Override
            public String getColumnName(int column) {
                return nomeColunas[column];
            }

            @Override
            public int getRowCount() {
                return (int) sistema.getUtilizadores().getTotalGestores();
            }

            @Override
            public int getColumnCount() {
                return nomeColunas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return sistema.getUtilizadores().todos().get(rowIndex).getNome();
                    case 1:
                        return sistema.getUtilizadores().todos().get(rowIndex).getUsername();
                    case 2:
                        return sistema.getUtilizadores().todos().get(rowIndex).getEmail();
                    
                    default:
                        
                        return "";
            }
        }
    };
    }
    
           public void atualizar() {
        //Informa o modelo que foram efetuadas alteracoes, o modelo informa a tabela e os dados são redesenhados
       modeloTabelaGestores.fireTableDataChanged(); 
    } 
            private void apagar()  {

           int rowIndex = jTableGestores.getSelectedRow();
           if (rowIndex == -1) {
               JOptionPane.showMessageDialog(this, "Selecione um gestor para remover.");
               return;
           }
           String username = (String) modeloTabelaGestores.getValueAt(rowIndex, 1);
           Gestor gestor = (Gestor) sistema.getUtilizadores().getGestor(username);
           if (gestor != null) {
               sistema.getUtilizadores().remover(gestor);
               serializacao.guardar(sistema);
           }
           atualizar();         
    } 
                
                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonAdicionarGestor = new javax.swing.JButton();
        jButtonEditarGestor = new javax.swing.JButton();
        jButtonRemoverGestor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGestores = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jButtonAtualizarGestor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerir Gestores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jButtonAdicionarGestor.setText("Adicionar");
        jButtonAdicionarGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarGestorActionPerformed(evt);
            }
        });

        jButtonEditarGestor.setText("Editar");
        jButtonEditarGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarGestorActionPerformed(evt);
            }
        });

        jButtonRemoverGestor.setText("Remover");
        jButtonRemoverGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverGestorActionPerformed(evt);
            }
        });

        jTableGestores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Nome", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTableGestores);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonAtualizarGestor.setText("Atualizar");
        jButtonAtualizarGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarGestorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addComponent(jButtonAdicionarGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditarGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoverGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(jButtonAtualizarGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdicionarGestor)
                            .addComponent(jButtonEditarGestor)
                            .addComponent(jButtonRemoverGestor)
                            .addComponent(jButtonAtualizarGestor)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVoltar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarGestorActionPerformed
        AdicionarGestor janelaGestor = new AdicionarGestor(sistema, serializacao);
        janelaGestor.setVisible(true);
    }//GEN-LAST:event_jButtonAdicionarGestorActionPerformed

    private void jButtonRemoverGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverGestorActionPerformed
        apagar();    
    }//GEN-LAST:event_jButtonRemoverGestorActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAtualizarGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarGestorActionPerformed
        atualizar();
    }//GEN-LAST:event_jButtonAtualizarGestorActionPerformed

    private void jButtonEditarGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarGestorActionPerformed
            int rowIndex = jTableGestores.getSelectedRow();
           if (rowIndex == -1) return;
           String username = (String) modeloTabelaGestores.getValueAt(rowIndex, 0);
        Gestor gestor = (Gestor) sistema.getUtilizadores().getGestor(username);
        new EditarGestor(sistema, serializacao, gestor).setVisible(true);
        
    }//GEN-LAST:event_jButtonEditarGestorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarGestor;
    private javax.swing.JButton jButtonAtualizarGestor;
    private javax.swing.JButton jButtonEditarGestor;
    private javax.swing.JButton jButtonRemoverGestor;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGestores;
    // End of variables declaration//GEN-END:variables

}
