/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.ADMIN;

import BACKEND.CentroVacinacao;
import BACKEND.Sistema;
import BACKEND.Utente;
import BACKEND.Utilizador;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Gonçalo
 */
public class InformacaoVacinacao extends javax.swing.JFrame {

    /**
     * Creates new form InformacaoVacinacao
     */
    public InformacaoVacinacao() {
        initComponents();
    }

    public InformacaoVacinacao(Sistema sistema) {
        initComponents();
        jPanel1.setLayout(new BorderLayout());
        JTextArea area = new JTextArea(resumo(sistema));
        area.setEditable(false);
        jPanel1.add(new JScrollPane(area), BorderLayout.CENTER);
    }

    private String resumo(Sistema sistema) {
        int totalUtentes = 0;
        int totalVacinados = 0;
        int totalMarcacoes = 0;
        for (Utilizador u : sistema.getUtilizadores().getListaUtilizador()) {
            if (u instanceof Utente) {
                totalUtentes++;
                Utente utente = (Utente) u;
                if (utente.getVacina() != null && utente.getTomas() > 0) {
                    totalVacinados++;
                }
            }
        }
        for (CentroVacinacao centro : sistema.getRepositorioCentrosVacinacao().todos()) {
            totalMarcacoes += centro.getAgendaMarcacoes().totalMarcacoes();
        }
        StringBuilder sb = new StringBuilder();
        sb.append("Informação de Vacinação\n\n");
        sb.append("Total de utilizadores: ").append(sistema.getUtilizadores().getTotalUtilizador()).append("\n");
        sb.append("Total de gestores: ").append(sistema.getUtilizadores().getTotalGestores()).append("\n");
        sb.append("Total de utentes: ").append(totalUtentes).append("\n");
        sb.append("Total de centros: ").append(sistema.getRepositorioCentrosVacinacao().sizeRepositorio()).append("\n");
        sb.append("Tipos de vacinas registados: ").append(sistema.getRepositoriovacinas().size()).append("\n");
        sb.append("Total de marcações: ").append(totalMarcacoes).append("\n");
        sb.append("Utentes com pelo menos uma vacina registada: ").append(totalVacinados).append("\n");
        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informação de Vacinação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1217, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(574, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
