/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.UTENTE;

import BACKEND.RepositorioDoencas;
import BACKEND.Sistema;
import BACKEND.Utente;
import SERIALIZACAO.Serializacao;
import javax.swing.JOptionPane;

/**
 *
 * @author Gonçalo
 */
public class AdicionarDoenca extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;
    
    public AdicionarDoenca(Sistema sistema, Serializacao serializacao) {
        initComponents();
        this.sistema = sistema;
        this.serializacao = serializacao;
    }
    
    public void guardar() {
        if (jTextFieldDoencaAAdicionar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza, por favor, a doença que pretende adicionar!");
            jTextFieldDoencaAAdicionar.requestFocus();
            return;
        }
        jTextFieldDoencaAAdicionar.setEditable(true);
        Utente u = (Utente) sistema.getUtilizadorligado();
        u.getDoencas().adicionarDoenca(jTextFieldDoencaAAdicionar.getText().trim());
        serializacao.guardar(sistema);
        JOptionPane.showMessageDialog(this, "Doença introduzida com sucesso. Por favor, atualize os seus dados!");
        dispose();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdicionarDoenca = new javax.swing.JButton();
        jTextFieldDoencaAAdicionar = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAdicionarDoenca.setText("Adicionar Doença");
        jButtonAdicionarDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarDoencaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionarDoenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, -1));
        getContentPane().add(jTextFieldDoencaAAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 190, -1));

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 91, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRONTEND/images/IntroduzirDoenca.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarDoencaActionPerformed
        guardar();     
    }//GEN-LAST:event_jButtonAdicionarDoencaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarDoenca;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldDoencaAAdicionar;
    // End of variables declaration//GEN-END:variables
}
