/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.UTENTE;

import BACKEND.CentroVacinacao;
import BACKEND.Sistema;
import BACKEND.Utente;
import SERIALIZACAO.Serializacao;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Gonçalo
 */
public class AgendarMarcacao extends javax.swing.JFrame {
    private Sistema sistema;
    private Serializacao serializacao;
    private Utente utente;
    /**
     * Creates new form AgendarMarcacao
     */
    public AgendarMarcacao(Sistema sistema, Serializacao serializacao) {
        initComponents();
        this.sistema = sistema;
        this.serializacao = serializacao;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonFazerMarcacao = new javax.swing.JButton();
        jDateChooserAgendarMarcacao = new com.toedter.calendar.JDateChooser();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecionar Data:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, -1));

        jButtonFazerMarcacao.setText("Realizar Marcação");
        jButtonFazerMarcacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFazerMarcacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFazerMarcacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 136, -1));
        getContentPane().add(jDateChooserAgendarMarcacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 170, -1));

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 89, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRONTEND/images/AgendarMarcacao.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFazerMarcacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFazerMarcacaoActionPerformed
        Date data = jDateChooserAgendarMarcacao.getDate();
        if (data == null) {
            JOptionPane.showMessageDialog(this, "Escolha uma data para a marcação.", "DATA EM FALTA", JOptionPane.WARNING_MESSAGE);
            return;
        }
        LocalDate data_administracao = data.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        utente = (Utente)sistema.getUtilizadores().getUtilizador(sistema.getUtilizadorligado().getUsername());
        if (utente == null) {
            JOptionPane.showMessageDialog(this, "Utente inválido.", "ERRO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CentroVacinacao cv = utente.getCentrovacinacao();
        if (cv == null) {
            JOptionPane.showMessageDialog(this, "Antes de agendar uma marcação, selecione um centro de vacinação.", "CENTRO EM FALTA", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean marcada = cv.fazerMarcacao(data_administracao, utente);
        if (marcada) {
            serializacao.guardar(sistema);
            JOptionPane.showMessageDialog(this, "Marcação efetuada com sucesso.");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível marcar nessa data. Verifique se já tem marcação ou se o limite diário foi atingido.", "MARCAÇÃO NÃO EFETUADA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonFazerMarcacaoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFazerMarcacao;
    private javax.swing.JButton jButtonVoltar;
    private com.toedter.calendar.JDateChooser jDateChooserAgendarMarcacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
