/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.UTENTE;

import BACKEND.CentroVacinacao;
import BACKEND.Sistema;
import BACKEND.Utente;

import SERIALIZACAO.Serializacao;

/**
 *
 * @author Gonçalo
 */
public class ConsultarCentroVacinacao extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;
    private Utente utente;

    /**
     * Creates new form ConsultarCentroVacinacao
     */
    public ConsultarCentroVacinacao(Sistema sistema, Serializacao serializacao) {
        initComponents();
        this.sistema = sistema;
        this.serializacao = serializacao;
        utente = (Utente) sistema.getUtilizadorligado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsultarCentro = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jTextFieldCentroVac = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonConsultarCentro.setText("Consultar Centro");
        jButtonConsultarCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarCentroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultarCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 150, -1));

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 87, -1));

        jTextFieldCentroVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCentroVacActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCentroVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 301, -1));

        jButton1.setText("Adicionar Centro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 154, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRONTEND/images/ConsultarCentro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldCentroVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCentroVacActionPerformed

    }//GEN-LAST:event_jTextFieldCentroVacActionPerformed

    private void jButtonConsultarCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarCentroActionPerformed
        try {
            jTextFieldCentroVac.setEditable(false);
            jTextFieldCentroVac.setText(utente.getCentrovacinacao().getLocalidade());

        } catch (NullPointerException e) {
            System.err.println("Utente não tem Centro de Vacinação Associado!");
        }
    }//GEN-LAST:event_jButtonConsultarCentroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AdicionarCentro(sistema, serializacao).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConsultarCentro;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldCentroVac;
    // End of variables declaration//GEN-END:variables
}
