/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.UTENTE;

import BACKEND.CentroVacinacao;
import BACKEND.RepositorioDoencas;
import BACKEND.Sistema;
import BACKEND.Utente;
import FRONTEND.ADMIN.CriarCentroVacinacao;
import SERIALIZACAO.Serializacao;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Gonçalo
 */
public class DadosUtente extends javax.swing.JFrame {
    
    private Sistema sistema;
    private Serializacao serializacao;
    private AbstractTableModel modeloTabela;
    private AbstractTableModel tabelaDadosUtente;
    private Utente utente;
    
    
    public DadosUtente(Sistema sistema, Serializacao serializacao) {
        initComponents();
        this.sistema = sistema;
        this.serializacao = serializacao;
        utente = (Utente) sistema.getUtilizadorligado();
        this.modeloTabela = criarModeloTabela();
        jTableDoencas.setModel(modeloTabela);
        CentroVacinacao cv = utente.getCentrovacinacao();
        if (cv != null && cv.getAgendaMarcacoes().dataMarcacao(utente) != null) {
            jTextFielddatamarcacao.setText(cv.getAgendaMarcacoes().dataMarcacao(utente).toString());
        } else {
            jTextFielddatamarcacao.setText("Sem marcação");
        }
        jTextFielddatamarcacao.setEditable(false);
        
    }
    
    private AbstractTableModel criarModeloTabela() {
        String[] nomeColunas = {"Doenças"};
        
        return new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return utente == null ? 0 : utente.getDoencas().getRepositorio().size(); //return ao numero de linhas, isto é, ao numero de doenças 
            }

            @Override
            public int getColumnCount() {
                return nomeColunas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return utente.getDoencas().getRepositorio().get(rowIndex);
                    
                    default:
                        
                        return "";
                }
            
            }
        };
    }
    
    public void atualizar() {
        //Informa o modelo que foram efetuadas alteracoes, o modelo informa a tabela e os dados são redesenhados
       modeloTabela.fireTableDataChanged();
       serializacao.guardar(sistema); 
    } 
    /*public void guardar() {
        if (jTextFieldDoencaAAdicionar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza, por favor alguma Doença!");
            jTextFieldDoencaAAdicionar.requestFocus();
            return;
        }
        
        Utente u = (Utente) sistema.getUtilizadorligado();
        u.getDoenças().AdicionarDoença(jTextFieldDoencaAAdicionar.getText());
        System.out.println(u.getDoenças());
    }*/
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDoencas = new javax.swing.JTable();
        jButtonAdicionarDoenca = new javax.swing.JButton();
        jButtonAtualizarDoencas = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonMostrarDados = new javax.swing.JButton();
        jTextFieldMorada = new javax.swing.JTextField();
        jTextFieldLocalidade = new javax.swing.JTextField();
        jTextFieldDataNascimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNTelemovel = new javax.swing.JTextField();
        jButtonOcultarDados = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFielddatamarcacao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDoencas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableDoencas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 315, 360));

        jButtonAdicionarDoenca.setText("Adicionar Doença");
        jButtonAdicionarDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarDoencaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionarDoenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 130, -1));

        jButtonAtualizarDoencas.setText("Atualizar");
        jButtonAtualizarDoencas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarDoencasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizarDoencas, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 120, -1));

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 134, -1));

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 180, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 50, -1));

        jLabel2.setText("Morada:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel3.setText("Número de SNS / Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, -1));

        jButtonMostrarDados.setText("Ver Dados Pessoais");
        jButtonMostrarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 160, -1));
        getContentPane().add(jTextFieldMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 180, -1));
        getContentPane().add(jTextFieldLocalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 180, -1));
        getContentPane().add(jTextFieldDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 180, -1));

        jLabel4.setText("Localidade:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 70, -1));

        jLabel5.setText("Data de Nascimento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 130, -1));

        jLabel6.setText("Número de Telemóvel:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 140, -1));
        getContentPane().add(jTextFieldNTelemovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 180, -1));

        jButtonOcultarDados.setText("Ocultar");
        jButtonOcultarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcultarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOcultarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 140, -1));

        jLabel7.setText("Data Marcação:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 120, 20));

        jTextFielddatamarcacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddatamarcacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielddatamarcacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarDoencaActionPerformed
         AdicionarDoenca janela = new AdicionarDoenca(sistema, serializacao);
        janela.setVisible(true); 
    }//GEN-LAST:event_jButtonAdicionarDoencaActionPerformed

    private void jButtonAtualizarDoencasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarDoencasActionPerformed
        atualizar();
    }//GEN-LAST:event_jButtonAtualizarDoencasActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
   
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jButtonMostrarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarDadosActionPerformed
       
        jTextFieldNome.setEditable(false);
        jTextFieldNome.setText(utente.getNome());
        
        jTextFieldUsername.setEditable(false);
        jTextFieldUsername.setText(utente.getNumSNS());
        
        jTextFieldMorada.setEditable(false);
        jTextFieldMorada.setText(utente.getMorada());
        
        jTextFieldLocalidade.setEditable(false);
        jTextFieldLocalidade.setText(utente.getLocalidade());
        
        jTextFieldDataNascimento.setEditable(false);
        jTextFieldDataNascimento.setText((utente.getData_Nasc()).toString());
        
        jTextFieldNTelemovel.setEditable(false);
        jTextFieldNTelemovel.setText(utente.getNumTelemovel());
        
        
        
    }//GEN-LAST:event_jButtonMostrarDadosActionPerformed

    private void jButtonOcultarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcultarDadosActionPerformed
        jTextFieldNome.setEditable(false);
        jTextFieldNome.setText(null);
        
        jTextFieldUsername.setEditable(false);
        jTextFieldUsername.setText(null);
        
        jTextFieldMorada.setEditable(false);
        jTextFieldMorada.setText(null);
        
        jTextFieldLocalidade.setEditable(false);
        jTextFieldLocalidade.setText(null);
        
        jTextFieldDataNascimento.setEditable(false);
        jTextFieldDataNascimento.setText(null);
        
        jTextFieldNTelemovel.setEditable(false);
        jTextFieldNTelemovel.setText(null);
    }//GEN-LAST:event_jButtonOcultarDadosActionPerformed

    private void jTextFielddatamarcacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddatamarcacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddatamarcacaoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarDoenca;
    private javax.swing.JButton jButtonAtualizarDoencas;
    private javax.swing.JButton jButtonMostrarDados;
    private javax.swing.JButton jButtonOcultarDados;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDoencas;
    private javax.swing.JTextField jTextFieldDataNascimento;
    private javax.swing.JTextField jTextFieldLocalidade;
    private javax.swing.JTextField jTextFieldMorada;
    private javax.swing.JTextField jTextFieldNTelemovel;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JTextField jTextFielddatamarcacao;
    // End of variables declaration//GEN-END:variables
}
