/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.GESTOR;

import BACKEND.CentroVacinacao;
import BACKEND.Sistema;
import BACKEND.Utilizador;
import SERIALIZACAO.Serializacao;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Gonçalo
 */
public class ConsultarAusencias extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarAusencias
     */
    public ConsultarAusencias() {
        initComponents();
    }

    public ConsultarAusencias(Sistema sistema, Serializacao serializacao) {
        initComponents();
        jTable1.setModel(criarModeloTabela(sistema));
    }

    private AbstractTableModel criarModeloTabela(Sistema sistema) {
        String[] nomeColunas = {"Número SNS", "Nome", "Data"};
        CentroVacinacao centro = sistema.getRepositorioCentrosVacinacao().procurarCentro(sistema.getUtilizadorligado().getUsername());
        ArrayList<Utilizador> utilizadores = centro == null ? new ArrayList<>() : centro.getAgendaMarcacoes().todosValues();
        ArrayList<LocalDate> datas = centro == null ? new ArrayList<>() : centro.getAgendaMarcacoes().todosKeysPorMarcacao();
        ArrayList<Integer> indicesAusencias = new ArrayList<>();
        LocalDate hoje = LocalDate.now();
        for (int i = 0; i < datas.size(); i++) {
            if (datas.get(i).isBefore(hoje)) {
                indicesAusencias.add(i);
            }
        }

        return new AbstractTableModel() {
            @Override
            public String getColumnName(int column) {
                return nomeColunas[column];
            }

            @Override
            public int getRowCount() {
                return indicesAusencias.size();
            }

            @Override
            public int getColumnCount() {
                return nomeColunas.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                int idx = indicesAusencias.get(rowIndex);
                switch (columnIndex) {
                    case 0:
                        return utilizadores.get(idx).getUsername();
                    case 1:
                        return utilizadores.get(idx).getNome();
                    case 2:
                        return datas.get(idx).toString();
                    default:
                        return "";
                }
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número SNS", "Nome", "Horário"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
