/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.GESTOR;

import BACKEND.CentroVacinacao;
import BACKEND.Sistema;
import BACKEND.Utente;
import SERIALIZACAO.Serializacao;
import java.util.ArrayList;

/**
 *
 * @author Gonçalo
 */
public class EstatisticasCentroVac extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao serializacao;

    public EstatisticasCentroVac(Sistema sistema, Serializacao serializacao){
        initComponents();
        this.sistema = sistema;
        this.serializacao = serializacao;
        
        double percentagem;
        int soma = 0;
        CentroVacinacao centro = sistema.getRepositorioCentrosVacinacao().procurarCentro(sistema.getUtilizadorligado().getUsername());
        ArrayList<Utente> utentes = sistema.getUtilizadores().utentesPorCentro(centro);
        if (utentes.isEmpty()) {
            labelPercentagem.setText("0%");
            return;
        }
       for (Utente u : utentes)
       {
           if (u.getVacina() != null && u.getTomas() >= u.getVacina().getTomas())
           {
               soma = soma + 1;
           }
       }
       
        percentagem = (soma * 100.0) / utentes.size();
        labelPercentagem.setText(String.format("%.2f%%", percentagem));
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelPercentagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonVoltar.setText("Voltar");

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel1.setText("Percentagem de Utentes Vacinados:");

        labelPercentagem.setFont(new java.awt.Font("Eras Bold ITC", 1, 30)); // NOI18N
        labelPercentagem.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(labelPercentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPercentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelPercentagem;
    // End of variables declaration//GEN-END:variables
}
