/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND.GESTOR;

import BACKEND.CentroVacinacao;
import BACKEND.Sistema;

import SERIALIZACAO.Serializacao;
import javax.swing.JOptionPane;

/**
 *
 * @author Gonçalo
 */
public class GerirMarcacoes extends javax.swing.JFrame {
    private Sistema sistema;
    private Serializacao serializacao;

    /**
     * Creates new form GerirMarcacoes
     */
    public GerirMarcacoes(Sistema sistema, Serializacao serializacao) {
        initComponents();
        this.sistema = sistema;
        this.serializacao = serializacao;
    }
    
    public void consultarUtentesEmFalta() {
        CentroVacinacao centro = sistema.getRepositorioCentrosVacinacao().procurarCentro(sistema.getUtilizadorligado().getUsername());

        if (centro.getAgendaMarcacoes()== null) {
            JOptionPane.showMessageDialog(this, "Ainda não existem consultas!");
            return;
        }

      

        /* ConsultarAusencias cuf = new ConsultarAusencias(sistema, serializacao);
        cuf.setVisible(true);
        this.dispose();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsultarMarcacoesTotal = new javax.swing.JButton();
        jButtonConsultarAusencias = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConsultarMarcacoesTotal.setText("Consultar Listagem de Marcações");
        jButtonConsultarMarcacoesTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarMarcacoesTotalActionPerformed(evt);
            }
        });

        jButtonConsultarAusencias.setText("Consultar Ausências");
        jButtonConsultarAusencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarAusenciasActionPerformed(evt);
            }
        });

        jButton3.setText("Consultar Marcações de Amanhã");

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButtonConsultarMarcacoesTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConsultarAusencias, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultarMarcacoesTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarAusencias, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonConsultarMarcacoesTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarMarcacoesTotalActionPerformed
        new ConsultarListaMarcacoes(sistema, serializacao).setVisible(true);
    }//GEN-LAST:event_jButtonConsultarMarcacoesTotalActionPerformed

    private void jButtonConsultarAusenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarAusenciasActionPerformed
        new ConsultarAusencias(sistema, serializacao).setVisible(true);
    }//GEN-LAST:event_jButtonConsultarAusenciasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonConsultarAusencias;
    private javax.swing.JButton jButtonConsultarMarcacoesTotal;
    private javax.swing.JButton jButtonVoltar;
    // End of variables declaration//GEN-END:variables
}
